# Generated by Django 2.0.5 on 2018-06-03 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='todoList',
            field=models.ForeignKey(db_column='fk_id_todo_list', on_delete=django.db.models.deletion.PROTECT, to='api.TodoList'),
        ),
    ]
