# Generated by Django 2.0.5 on 2018-06-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180603_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=255),
        ),
    ]
